#pragma once               
// Ensures this header is included only once during compilation.
// Prevents duplicate class definitions (same effect as include guards).

#include "crewMember.h"   
// Includes the definition of the base class crewMember,
// which the human class inherits from.



// ============================================================================
// Class Declaration: human
// This class represents a human crew member in the recruitment system.
// It INHERITS from crewMember using *public inheritance*, meaning:
// - All public methods in crewMember remain public in human.
// - All protected methods in crewMember remain protected in human.
// ============================================================================
class human : public crewMember
{
private:

    string humanSector;     
    // Stores the sector assignment for a human crew member.
    // This field is specific to humans only (not aliens).

public:

    // ------------------------------------------------------------------------
    // Default Constructor
    // Declared here, implemented in human.cpp
    // ------------------------------------------------------------------------
    human();                // Creates a human with default values



    // ------------------------------------------------------------------------
    // Parameterized Constructor
    // Accepts first name, last name, sector, training score, and aptitude.
    // Calls the crewMember constructor for shared attributes.
    // ------------------------------------------------------------------------
    human(string fName, 
          string lName, 
          string hSector,
          float tScore, 
          int mAptitude);



    // ------------------------------------------------------------------------
    // Getter: getHumanSector
    // Returns the humanSector string.
    // Marked as const: guarantees it does NOT modify the object.
    // ------------------------------------------------------------------------
    string getHumanSector() const;



    // ------------------------------------------------------------------------
    // Destructor (not needed)
    //
    // human does not allocate dynamic memory (no new/delete),
    // so the default destructor generated by the compiler is sufficient.
    //
    // Left here as a placeholder for reference, but commented out.
    // ------------------------------------------------------------------------
    // ~human();  



    // ------------------------------------------------------------------------
    // Overloaded Output Stream Operator (<<)
    //
    // Allows you to print a human object using:
    //     cout << h;
    //
    // Declared as a *friend* so the function has access to the private
    // attributes of this class.
    // Implemented in human.cpp.
    // ------------------------------------------------------------------------
    friend ostream& operator<<(ostream& os, const human& h);

};  // End of class human
